Fixed some translations (not all)
discloud/traducoes pull request #58
Opened 2023-09-16 21:03 UTC by Jbziscool

Some translations didn't make sense (such as plans being translated as planes lol) so I have fixed some of the translations, not all of them though however I may do more in the future.

Tradução para o português.

Algumas traduções não faziam sentido (por exemplo, planos sendo traduzidos como aviões rs), portanto, corrigi algumas das traduções, mas não todas, mas posso fazer mais no futuro.

(A mensagem em português foi traduzida usando um tradutor, pois não falo português, apenas inglês e finlandês)

2023-09-16 21:10 UTC, astindev commented
Looks good to me, ty

2023-09-16 21:46 UTC, Gorniaky commented on bot/en-US/commands.json
> +            "timeout": "Please wait `{{minutes}} minutes and {{seconds}} seconds` to generate a There are no registrynew backup of your application.",
I think you meant:

```
Wait `{{minutes}} minutes and {{seconds}} seconds` to generate a new backup of your application.
```

2023-09-22 10:09 UTC, Jbziscool commented on bot/en-US/commands.json
> +            "timeout": "Please wait `{{minutes}} minutes and {{seconds}} seconds` to generate a There are no registrynew backup of your application.",
Fixed thanks

2023-09-23 15:07 UTC, Jbziscool commented
@pedroricardo

2023-09-30 15:18 UTC, astindev requested changes

2023-09-30 15:35 UTC, merged